# Si existen las variables DB_URL, DB_USER y DB_PASS, las usa (Render). 
# Si no existen, usa las de tu ordenador (localhost y root).

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/profesorado_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true